pipeline {
    
    agent { label "master" }
    
    stages {
        
        stage('Checkout') {
            
            steps {
                
                  git 'https://github.com/Parashuraam/jenkins-tomcat-deployment.git'
            }
            
        }
    }
}